DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.1 # 0.2 最大余弦距离 
  MIN_CONFIDENCE: 0.5   #0.3  YOLOv5最小检测置信度，增大置信度可去除杂散干扰。
  NMS_MAX_OVERLAP: 1.  # 0.5
  MAX_IOU_DISTANCE: 0.5 # 0.7 IOU最大距离，此值小则不易匹配，将产生新的ID。
  MAX_AGE: 70
  N_INIT: 6     # 3 track连续confirm数量，增大有助于减少新ID出现。
  NN_BUDGET: 100 # track最大feature数量。
  
